# Generated by Django 5.2.15 on 2026-06-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='image_url',
        ),
        migrations.AddField(
            model_name='bag',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bags/images/'),
        ),
    ]
