# Generated by Django 5.2.15 on 2026-06-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_bag_image_url_bag_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show this bag on the landing page showcase'),
        ),
    ]
