# Generated by Django 5.2.15 on 2026-06-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_bag_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='color_hex',
            field=models.CharField(choices=[('linear-gradient(135deg, #fdfbfb, #ebedee)', 'Pearl / White'), ('linear-gradient(135deg, #f8f9fa, #ced4da)', 'Crystal / Clear'), ('linear-gradient(135deg, #434343, #000000)', 'Midnight / Onyx Black'), ('linear-gradient(135deg, #fdfbfb, #e3d5ca)', 'Champagne'), ('linear-gradient(135deg, #cfd9df, #e2ebf0)', 'Silver'), ('linear-gradient(135deg, #f6d365, #fda085)', 'Gold'), ('linear-gradient(135deg, #fbc2eb, #a6c1ee)', 'Blush Rose'), ('linear-gradient(135deg, #f093fb, #f5576c)', 'Fuchsia Pink'), ('linear-gradient(135deg, #ff0844, #ffb199)', 'Ruby Red'), ('linear-gradient(135deg, #ffecd2, #fcb69f)', 'Peach / Coral'), ('linear-gradient(135deg, #9b23ea, #5f72bd)', 'Amethyst Purple'), ('linear-gradient(135deg, #2af598, #009efd)', 'Sapphire Blue'), ('linear-gradient(135deg, #667eea, #764ba2)', 'Deep Plum'), ('linear-gradient(135deg, #0ba360, #3cba92)', 'Emerald Green'), ('linear-gradient(135deg, #d9f99d, #84cc16)', 'Rich Lime'), ('linear-gradient(135deg, #96fbc4, #f9f586)', 'Mint / Pistachio')], default='linear-gradient(135deg, #f8f9fa, #ced4da)', help_text='Select the visual swatch color for the website', max_length=100),
        ),
        migrations.AlterField(
            model_name='bag',
            name='color',
            field=models.CharField(help_text="e.g., 'Lime Green', 'Pearl'", max_length=50),
        ),
        migrations.AlterField(
            model_name='bag',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show this bag on the landing page'),
        ),
    ]
