# Generated by Django 5.2.15 on 2026-06-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_bag_color_hex_alter_bag_color_alter_bag_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Home Studio', help_text='A label for your reference', max_length=255)),
                ('store_latitude', models.DecimalField(decimal_places=6, default=-1.2655, help_text='Your exact Google Maps Latitude', max_digits=9)),
                ('store_longitude', models.DecimalField(decimal_places=6, default=36.8023, help_text='Your exact Google Maps Longitude', max_digits=9)),
                ('shipping_base_fee', models.DecimalField(decimal_places=2, default=150.0, help_text='Base drop-off fee for the boda (KES)', max_digits=10)),
                ('shipping_rate_per_km', models.DecimalField(decimal_places=2, default=35.0, help_text='Amount to charge per driving KM (KES)', max_digits=10)),
                ('pickup_mtaani_fee', models.DecimalField(decimal_places=2, default=150.0, help_text='Flat fee for Pickup Mtaani agent drops (KES)', max_digits=10)),
            ],
            options={
                'verbose_name': 'Store Setting',
                'verbose_name_plural': 'Store Settings',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
