# Generated by Django 5.2.17 on 2026-09-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_storesettings_order_shipping_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='minimum_shipping_fee',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Amount to charge per driving KM (KES)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='shipping_base_fee',
            field=models.DecimalField(decimal_places=2, default=60.0, help_text='Base drop-off fee for the boda (KES)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='shipping_rate_per_km',
            field=models.DecimalField(decimal_places=2, default=20.5, help_text='Amount to charge per driving KM (KES)', max_digits=10),
        ),
    ]
