# Generated by Django 5.2.17 on 2026-09-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_storesettings_minimum_shipping_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='store_latitude',
            field=models.DecimalField(decimal_places=6, default=-1.283338, help_text='Your exact Google Maps Latitude', max_digits=9),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='store_longitude',
            field=models.DecimalField(decimal_places=6, default=36.825122, help_text='Your exact Google Maps Longitude', max_digits=9),
        ),
    ]
