# Generated by Django 5.2.17 on 2026-09-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_storesettings_store_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='color_hex',
            field=models.CharField(choices=[('#ff3da5', 'Hot Pink (Vibrant Solid Pink)'), ('#e8259a', 'Fuchsia (Deep Purplish-Pink)'), ('#ff8ab8', 'Rose Quartz (Soft Blush Pink)'), ('#fde8ef', 'Pearl & Blush (Very Light Pink/White)'), ('#d8211a', 'Crimson / Ruby (Classic Deep Red)'), ('#d9381a', 'Ember (Orange-Toned Red)'), ('#ff7a1a', 'Tangerine (Bright Orange)'), ('#ff7a4a', 'Coral Glow (Soft Orange-Pink)'), ('#ff3d8a', 'Sunset (Vibrant Pink-Orange)'), ('#f5e58a', 'Butter (Soft Pastel Yellow)'), ('#8a52d4', 'Amethyst (Bright Jewel Purple)'), ('#a64ad9', 'Orchid (Soft Muted Purple)'), ('#8ccf2f', 'Lime (Bright Yellow-Green)'), ('#7fb84a', 'Citrus Grove (Earthy Amber-Green)'), ('#ecf3f8', 'Clear / Ice (Translucent White)'), ('#4a2418', 'Cocoa (Rich Dark Brown)'), ('#0f0f10', 'Onyx & Gold (Deepest Black)'), ('#1a1a1a', 'Jet Multi (Charcoal/Sparkle Black)'), ('#141414', 'Noir & Rose (Soft Matte Black)')], default='linear-gradient(135deg, #f8f9fa, #ced4da)', help_text='Select the visual swatch color for the website', max_length=100),
        ),
    ]
